"""phase 1 source records, ground truth, ingest hygiene

Revision ID: 90600b898c7d
Revises:
Create Date: 2026-08-23 12:14:22.089274
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "90600b898c7d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_txns",
        sa.Column("bank_txn_id", sa.String(length=64), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("credit", "debit", name="txn_direction", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("utr", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("bank_txn_id", name=op.f("pk_bank_txns")),
    )
    with op.batch_alter_table("bank_txns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_txns_utr"), ["utr"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_txns_value_date"), ["value_date"], unique=False)

    op.create_table(
        "gateway_txns",
        sa.Column("txn_id", sa.String(length=64), nullable=False),
        sa.Column("order_ref", sa.String(length=64), nullable=True),
        sa.Column("gross_minor", sa.BigInteger(), nullable=False),
        sa.Column("fee_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("net_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payout_id", sa.String(length=64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("txn_id", name=op.f("pk_gateway_txns")),
    )
    with op.batch_alter_table("gateway_txns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gateway_txns_captured_at"), ["captured_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_gateway_txns_order_ref"), ["order_ref"], unique=False)
        batch_op.create_index(batch_op.f("ix_gateway_txns_payout_id"), ["payout_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_gateway_txns_status"), ["status"], unique=False)

    op.create_table(
        "ground_truth_labels",
        sa.Column("label_id", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column(
            "break_type",
            sa.Enum(
                "missing_in_gateway",
                "orphan_payment",
                "unidentified_credit",
                "amount_mismatch",
                "short_payment",
                "overpayment",
                "fee_variance",
                "fx_variance",
                "unsettled",
                "payout_mismatch",
                "duplicate_payment",
                "refund_unapplied",
                "chargeback",
                "timing_difference",
                "unclassified",
                name="break_type",
                native_enum=False,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column(
            "expected_outcome",
            sa.Enum(
                "matched",
                "matched_with_exception",
                "unmatched",
                "ambiguous",
                name="expected_outcome",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "resolution_category",
            sa.Enum(
                "none",
                "auto_clear",
                "propose_journal",
                "investigate",
                "escalate_human",
                "write_off",
                "no_action",
                name="resolution_category",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("affected_ids", sa.JSON(), nullable=False),
        sa.Column("amount_at_risk_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("injector", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("label_id", name=op.f("pk_ground_truth_labels")),
    )
    with op.batch_alter_table("ground_truth_labels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ground_truth_labels_break_type"), ["break_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ground_truth_labels_injector"), ["injector"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ground_truth_labels_scenario"), ["scenario"], unique=False
        )

    op.create_table(
        "ingest_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_dir", sa.Text(), nullable=False),
        sa.Column("scenario", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_ingest_runs")),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("gross_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("order_id", name=op.f("pk_orders")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_customer_id"), ["customer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_placed_at"), ["placed_at"], unique=False)

    op.create_table(
        "payout_batches",
        sa.Column("payout_id", sa.String(length=64), nullable=False),
        sa.Column("expected_net_minor", sa.BigInteger(), nullable=False),
        sa.Column("txn_count", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("settled_on", sa.Date(), nullable=False),
        sa.Column("utr", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("payout_id", name=op.f("pk_payout_batches")),
    )
    with op.batch_alter_table("payout_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payout_batches_settled_on"), ["settled_on"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_payout_batches_utr"), ["utr"], unique=False)

    op.create_table(
        "quarantined_rows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingest_runs.run_id"],
            name=op.f("fk_quarantined_rows_run_id_ingest_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantined_rows")),
    )
    with op.batch_alter_table("quarantined_rows", schema=None) as batch_op:
        batch_op.create_index("ix_quarantined_rows_run_source", ["run_id", "source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quarantined_rows", schema=None) as batch_op:
        batch_op.drop_index("ix_quarantined_rows_run_source")

    op.drop_table("quarantined_rows")
    with op.batch_alter_table("payout_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payout_batches_utr"))
        batch_op.drop_index(batch_op.f("ix_payout_batches_settled_on"))

    op.drop_table("payout_batches")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_placed_at"))
        batch_op.drop_index(batch_op.f("ix_orders_customer_id"))

    op.drop_table("orders")
    op.drop_table("ingest_runs")
    with op.batch_alter_table("ground_truth_labels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ground_truth_labels_scenario"))
        batch_op.drop_index(batch_op.f("ix_ground_truth_labels_injector"))
        batch_op.drop_index(batch_op.f("ix_ground_truth_labels_break_type"))

    op.drop_table("ground_truth_labels")
    with op.batch_alter_table("gateway_txns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gateway_txns_status"))
        batch_op.drop_index(batch_op.f("ix_gateway_txns_payout_id"))
        batch_op.drop_index(batch_op.f("ix_gateway_txns_order_ref"))
        batch_op.drop_index(batch_op.f("ix_gateway_txns_captured_at"))

    op.drop_table("gateway_txns")
    with op.batch_alter_table("bank_txns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_txns_value_date"))
        batch_op.drop_index(batch_op.f("ix_bank_txns_utr"))

    op.drop_table("bank_txns")
    # ### end Alembic commands ###
